language: objective-c
osx_image: xcode9.2

before_install: true
install:
  - rvm get stable || true
  - brew update || true
  - brew install carthage || true
  - brew outdated carthage || brew upgrade carthage
before_script:
  - chmod +x ./script/build
xcode_project: FeathersSwiftSocketIO.xcodeproj
matrix:
  include:
    - script:
      - pod repo update
      - travis_wait 30 pod lib lint FeathersSwiftSocketIO.podspec
      env:
        - JOB=PODSPEC
    - script:
      - carthage bootstrap --no-use-binaries --platform mac
      - script/build
      xcode_scheme: FeathersSwiftSocketIO-macOS
      env:
        - XCODE_SDK=macosx
        - XCODE_ACTION=build
        - XCODE_DESTINATION="arch=x86_64"
    - script:
      - carthage bootstrap --no-use-binaries --platform iOS
      - script/build
      xcode_scheme: FeathersSwiftSocketIO-iOS
      env:
        - XCODE_SDK=iphonesimulator
        - XCODE_ACTION=build
        - XCODE_DESTINATION="platform=iOS Simulator,name=iPhone 6s"
    - script:
      - carthage bootstrap --no-use-binaries --platform tvOS
      - script/build
      xcode_scheme: FeathersSwiftSocketIO-tvOS
      env:
        - XCODE_SDK=appletvsimulator
        - XCODE_ACTION=build
        - XCODE_DESTINATION="platform=tvOS Simulator,name=Apple TV"
    - script:
      - carthage bootstrap --no-use-binaries --platform watchOS
      - script/build
      xcode_scheme: FeatherSwiftSocketIO-watchOS
      env:
        - XCODE_SDK=watchsimulator
        - XCODE_ACTION=build
        - XCODE_DESTINATION="platform=watchOS Simulator,name=Apple Watch Series 3 - 38mm"
    - script:
      - carthage checkout --no-use-binaries
      - carthage build --no-skip-current --platform mac
      env:
        - JOB=CARTHAGE-macOS
    - script:
        - carthage checkout --no-use-binaries
        - carthage build --no-skip-current --platform iOS
      env:
        - JOB=CARTHAGE-iOS
    - script:
      - carthage checkout --no-use-binaries
      - carthage build --no-skip-current --platform tvOS
      env:
        - JOB=CARTHAGE-tvOS
    - script:
      - carthage checkout --no-use-binaries
      - carthage build --no-skip-current --platform watchOS
      env:
        - JOB=CARTHAGE-watchOS
